image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  only:
    - master
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean install package "
  artifacts:
    paths:
      - target/*.jar

#docker-build:
#  stage: package
#  script:
#    - docker build -t registry.gitlab.com/innotex/pcod/calls-eoc .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/innotex/pcod/calls-eoc:latest
